### ISSUE TITLE
Margin property expands to max-resolution

### ISSUE THREAD

**Issue by radum** [atom/autocomplete-css#1]
Not sure if this should be here or under the main plugin issue list.

But if I try to use TAB on margin it expands to `max-resolution: res;`

![atom-autocomplete-css-margin](https://cloud.githubusercontent.com/assets/46779/6371285/16693db2-bcf2-11e4-9cfd-ef365d3ef0c3.gif)

and this is my list of plugins installed

``` txt
asteroids\
atom-handlebars\
autocomplete-css\
autocomplete-html\
autocomplete-plus\
autocomplete-snippets\
color-picker\
command-logger\
docblockr\
editor-stats\
editorconfig\
emmet\
file-icons\
fizzy\
graphite-ui\
highlight-selected\
ibm-dimensions-kit\
linter\
linter-bootlint\
linter-csslint\
linter-jscs\
linter-jshint\
linter-scss-lint\
merge-conflicts\
minimap\
minimap-color-highlight\
minimap-find-and-replace\
minimap-git-diff\
minimap-highlight-selected\
minimap-selection\
monokai\
react\
seti-syntax\
seti-ui\
sort-lines\
spacegray-dark-ui\
Sublime-Style-Column-Selection\
travis-ci-status\
unity-ui\
visual-bell\
Zen\
```

**Comment by benogle** [comment]
Not sure why it's matching that snippet, but I feel like maybe the property snippets can be removed and supplanted by autocomplete-css. Seems like the snippets were a stop-gap solution anyway. The this package is a much better way to complete the properties and values.

**Comment by radum** [comment]
I disabled them one by one and `emmet` is the one that breaks this. It can be closed and I will open there.

**Comment by radum** [comment]
Leaving this here for reference: https://github.com/emmetio/emmet-atom/issues/220
