### ISSUE TITLE
Object.add is deprecated.

### ISSUE THREAD

**Issue by zetay** [atom/autocomplete-css#10]
Are you trying to listen for the 'core:confirm' Atom command with `jQuery::on`?
`jQuery::trigger` can no longer be used to listen for Atom commands. Please
use `atom.commands.add` instead. See the docs at
https://atom.io/docs/api/latest/CommandRegistry

**Comment by thomasjo** [comment]
Same story here, another false positive. I'm assuming the problem lies with your _autocomplete_ provider. I'm closing this since it's not an issue that belongs here, but could you please provide the output of executing the following command?

``` bash
$ apm list
```

---

/cc @izuzak @atom/non-github-maintainers

**Comment by izuzak** [comment]
Can you also share the output of `atom -v`, @zetay?

**Comment by zetay** [comment]
0.194.0 @izuzak

**Comment by izuzak** [comment]
Thanks, @zetay. Could you also share the list of packages you had installed, as @thomasjo asked? We'd love to see the output of `apm list`.

**Comment by zetay** [comment]
apm list @izuzak 

[36mBuilt-in Atom packages[39m (85)
├── archive-view@0.56.0
├── atom-dark-syntax@0.26.0
├── atom-dark-ui@0.49.0
├── atom-light-syntax@0.26.0
├── atom-light-ui@0.41.0
├── autocomplete@0.44.0
├── autoflow@0.22.0
├── autosave@0.20.0
├── background-tips@0.24.0
├── base16-tomorrow-dark-theme@0.25.0
├── base16-tomorrow-light-theme@0.8.0
├── bookmarks@0.35.0
├── bracket-matcher@0.74.0
├── command-palette@0.35.0
├── deprecation-cop@0.43.0
├── dev-live-reload@0.46.0
├── encoding-selector@0.20.0
├── exception-reporting@0.24.0
├── feedback@0.38.0
├── find-and-replace@0.161.0
├── fuzzy-finder@0.83.0
├── git-diff@0.55.0
├── go-to-line@0.30.0
├── grammar-selector@0.46.0
├── image-view@0.54.0
├── incompatible-packages@0.24.0
├── keybinding-resolver@0.32.0
├── language-c@0.44.0
├── language-clojure@0.14.0
├── language-coffee-script@0.40.0
├── language-csharp@0.5.0
├── language-css@0.28.0
├── language-gfm@0.70.0
├── language-git@0.10.0
├── language-go@0.25.0
├── language-html@0.32.0
├── language-hyperlink@0.13.0
├── language-java@0.15.0
├── language-javascript@0.76.0
├── language-json@0.14.0
├── language-less@0.26.0
├── language-make@0.14.0
├── language-mustache@0.11.0
├── language-objective-c@0.15.0
├── language-perl@0.23.0
├── language-php@0.22.0
├── language-property-list@0.8.0
├── language-python@0.34.0
├── language-ruby@0.52.0
├── language-ruby-on-rails@0.21.0
├── language-sass@0.36.0
├── language-shellscript@0.14.0
├── language-source@0.9.0
├── language-sql@0.15.0
├── language-text@0.6.0
├── language-todo@0.19.0
├── language-toml@0.15.0
├── language-xml@0.28.0
├── language-yaml@0.22.0
├── link@0.30.0
├── markdown-preview@0.148.0
├── metrics@0.45.0
├── notifications@0.42.0
├── one-dark-syntax@0.4.0
├── one-dark-ui@0.7.0
├── one-light-syntax@0.5.0
├── one-light-ui@0.6.0
├── open-on-github@0.36.0
├── package-generator@0.38.0
├── release-notes@0.52.0
├── settings-view@0.196.0
├── snippets@0.88.0
├── solarized-dark-syntax@0.32.0
├── solarized-light-syntax@0.19.0
├── spell-check@0.56.0
├── status-bar@0.69.0
├── styleguide@0.44.0
├── symbols-view@0.95.0
├── tabs@0.68.0
├── timecop@0.31.0
├── tree-view@0.171.0
├── update-package-dependencies@0.9.0
├── welcome@0.27.0
├── whitespace@0.29.0
└── wrap-guide@0.32.0

[36mC:\Users\zetay.lim.atom\packages[39m (11)
├── autocomplete-css@0.6.0
├── autocomplete-html@0.6.0
├── autocomplete-plus@2.12.1
├── editorconfig@1.0.0
├── linter@0.12.1
├── linter-csslint@0.0.12
├── linter-htmlhint@0.0.13
├── linter-jshint@0.1.2
├── project-manager@1.15.5
├── seti-syntax@0.4.0
└── seti-ui@0.7.1
