### ISSUE TITLE
Autocomplete import file names

### ISSUE THREAD

**Issue by Nokel81** [atom/autocomplete-css#104]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When typing the `@import` statement it would be nice if the file names autocompleted starting from the cwd

### Versions

autocomplete-css: 0.16.2
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by winstliu** [comment]
Thanks for the submission!

That would definitely be useful in some people's workflows. However, it is not something that is within the scope that we have have envisioned for this package. For that reason, I'm going to close this. I believe this functionality can be achieved using the existing [autocomplete-paths](https://atom.io/packages/autocomplete-paths) package.

Thanks again for contributing to Atom :+1:
