### ISSUE TITLE
Autocomplete triggered in CSS/LESS files on semi colon

### ISSUE THREAD

**Issue by adamreisnz** [atom/autocomplete-css#15]
Consider the following behaviour:

![Example](https://www.dropbox.com/s/zj13mkn28veugoh/atom-css-autocomplete-issue.gif?dl=1)

When I reach the end of the line in my CSS/LESS file, I want to be able to hit enter and go to the next line, not select "width" every time or keep typing on the same line. Why is the autocomplete automatically triggered here? This behaviour is not exhibited in other files like javascript. No autocomplete box shows up after ending a line with a semi colon:

![Example](https://www.dropbox.com/s/3n8m66o6japkz88/atom-css-autocomplete-issue2.gif?dl=1)

I think this is not desirable, and the autocomplete should not be triggered when the last character is a semi colon in CSS. It has nothing to go on (no alphanumeric characters), so it's just suggesting a complete list of CSS selectors, which is rather pointless.

**Comment by thomashigginbotham** [comment]
I am noticing this issue in SCSS files as well.

**Comment by oraculus** [comment]
notice this bug as well, and in any case the property selected should suggest valid values and not again the same list of properties (in the first example is obvious, _width_ tigers again _width_).

**Comment by amneacsu** [comment]
Happens after an opening brace as well.

**Comment by vitorlee** [comment]
same issue as @adambuczynski , any solution so far?
