### ISSUE TITLE
,return

### ISSUE THREAD

**Issue by KevinMcCoy** [atom/autocomplete-css#18]
Auto fills in data too quickly, a pop out interrupt the flow when after typing in css with a comma.  Therefor when hitting return after typing in a comma, autofill inputs the 1st item from the auto fill list.

I would suggest maybe a way to disable auto fill on after a comma is typed to fix this issue or enable min char before the pop out. 

![screen shot 2015-06-21 at 10 12 14 pm](https://cloud.githubusercontent.com/assets/2472738/8275402/cd95056c-1872-11e5-95b0-8b2d82ae16f7.png)

**Comment by mattmischuk** [comment]
OMG yes! +1

**Comment by rchanou** [comment]
I have 0.9.0 and I still get the unwanted auto-complete after an opening Egyptian curly brace (with or without comma before); am I missing something?

**Comment by benogle** [comment]
Can you make a gif or explain exactly what you type, and when it shows?

**Comment by benogle** [comment]
@rchanou There are some changes that will be out in atom 1.0.4 that should fix what you're experiencing.

**Comment by rchanou** [comment]
Yeah, just noticed it working on 1.0.5 :) Thanks
