### ISSUE TITLE
Autocomplete box only showing properties (no values)

### ISSUE THREAD

**Issue by ck-jrd** [atom/autocomplete-css#20]
![muacfrpqja](https://cloud.githubusercontent.com/assets/5385895/8434064/42528e92-1f17-11e5-9d39-a02ee61fc8ce.gif)
Autocompleting a property in CSS causes another autocompletion box with only properties to open up. Can't see values after autocompleting property.

Installed community packages:
emmet
less-than-slash
linter-php
minimap
pigments
wordpress-api

**Comment by benogle** [comment]
Looks like this happens when the rule is on one line. It's really an issue with `language-css` et al. as they get the scopes wrong when the curly braces are on the same line. Leaving it here is fine for now, though.

**Comment by benogle** [comment]
Thanks for reporting this. A fix will be out in the next atom release next week.
