### ISSUE TITLE
How can I update values?

### ISSUE THREAD

**Issue by kritsky** [atom/autocomplete-css#22]
Hello, I am newbie in atom. I can't see properties for display like inline-block, block and so on. Like in your gif.

Maybe this can help:
You can update the prebuilt list of property names and values by running the update.coffee file at the root of the repository and then checking in the changed properties.json file.

But I can't understand how to do that. Can you help me?

**Comment by benogle** [comment]
Can you provide a little more information?
- What kind of file are you editing?
- Where are you in the file?
- Can you paste in an example, and explain where your cursor is? Or provide a gif?

You should not need to mess with updating the properties.json. That is only for the package author.

**Comment by kritsky** [comment]
I am trying to do this the same as in the gif: https://github.com/atom/autocomplete-css

CSS file in the project.

**Comment by benogle** [comment]
So what exactly do you see? Can you quit atom and run it via `atom --safe`? Does that help? Can you paste in an example that doesnt work?

**Comment by kritsky** [comment]
I have to type every value for the class. And I don't see dropdown values to choose.

For example when I type <code>body{}</code> and trying to add <code>display</code> I have to type it myself and also the value <code>block</code>. Because there is no dropdown values.

Where should I run it via <code>atom --safe</code>?

**Comment by benogle** [comment]
Can you do a few things for me?
- paste in your config file (cmd-shift-p -> open your config)
- follow https://atom.io/docs/latest/hacking-atom-debugging

**Comment by kritsky** [comment]
This package was disabled..
Thanks for help!
