### ISSUE TITLE
Unintended CSS suggestions

### ISSUE THREAD

**Issue by artivilla** [atom/autocomplete-css#28]
So I'm trying to hit 'tab' to add comments at the end of a line and it always shows me suggestions even before I've started typing the given style. I'm constantly hitting tab and it's add 'width' at random points. 

Screenshot enclosed.

![screen shot 2015-07-31 at 12 31 31 am](https://cloud.githubusercontent.com/assets/2120159/9000825/ae2c49f2-371b-11e5-9b5f-a2575fd512b1.png)

**Comment by benogle** [comment]
Thanks for the report. Hopefully this will be fixed by https://github.com/atom/autocomplete-css/pull/26 and out next week in atom 1.0.4. If it's still an issue when atom 1.0.4 is out, please reopen.
