### ISSUE TITLE
too many options when using sass

### ISSUE THREAD

**Issue by chrisdrackett** [atom/autocomplete-css#32]
When using css autocomplete only show available values for the current property:

![css](https://s3.amazonaws.com/f.cl.ly/items/3N2V401A1d420V0q0W47/Screen%20Shot%202015-08-19%20at%202.45.45%20PM.png)

however when using sass, many more values are shown:

![sass](https://s3.amazonaws.com/f.cl.ly/items/0N0r3W0h291D0z0Z3C19/Screen%20Shot%202015-08-19%20at%202.45.28%20PM.png)

ideally this would show the exact same menu seen when editing css.

**Comment by benogle** [comment]
This is an issue with the grammar. The grammar doesn't know it's in `property-value` mode.

**Comment by scottjehl** [comment]
+1 this would be great to fix. 

"left" values always autocomplete to the "legal" snippet, like this:
https://twitter.com/scottjehl/status/679727158512775168

Thanks!

**Comment by winstliu** [comment]
Cannot reproduce.  The Sass grammar has undergone many improvements since this was reported, so assuming fixed.
