### ISSUE TITLE
Can I have semicolon on autocomplete css? 

### ISSUE THREAD

**Issue by darkogerguric** [atom/autocomplete-css#36]
Hi.
I am fairly new to Atom, and coming from Sublime text I really miss one thing:
can I have semicolon on css autocomplete?
So when I do autocomplete on say "color " it becomes "color: ;" ?
Now I have just a colon so it looks like this : "color: "
Thank you.

**Comment by winstliu** [comment]
If you autocomplete the value it'll automatically add the semicolon for you.
