### ISSUE TITLE
Need PostCSS support like SCSS and Less

### ISSUE THREAD

**Issue by asifshirazi** [atom/autocomplete-css#37]
It will be great if you can add support for `.pcss` and `.postcss` files.

**Comment by jurStv** [comment]
+1, need this enhancement.

**Comment by ntwcklng** [comment]
+1

**Comment by Funx** [comment]
+1

**Comment by c9rgreen** [comment]
+1

**Comment by belozer** [comment]
+1

**Comment by Secbone** [comment]
+1

**Comment by mtshv** [comment]
+1

**Comment by iprishvin** [comment]
+1

**Comment by ai** [comment]
Also `.sss` for [SugarSS](https://github.com/postcss/sugarss) (Sass like) syntax. It is part of PostCSS too.

**Comment by iamalvisng** [comment]
+1

**Comment by lijianzhang** [comment]
+1

**Comment by rubenmoya** [comment]
+1

**Comment by lordgiotto** [comment]
Totally agree! 😄

**Comment by ai** [comment]
@50Wliu what steps we need to solve it. I can bring developers to do the work.

**Comment by eseQ** [comment]
@ai Yeah, i think this must need future. How we can help?

**Comment by winstliu** [comment]
See #80 for the latest work.

**Comment by ai** [comment]
@50Wliu so work is done? PR is green. Or what do we need?

**Comment by winstliu** [comment]
It needs a reviewer from the Atom team.

**Comment by ai** [comment]
@50Wliu I think if you will mention 2-3 persons by name and ask for review it could help

**Comment by ai** [comment]
@50Wliu any updates?

**Comment by winstliu** [comment]
If there were updates we'd definitely tell you.  Everyone's been quite busy these past few months.

**Comment by ai** [comment]
@50Wliu how we can help here? :)

(People write me about autocomplete too often, I will get more free time if I will fix it)

**Comment by winstliu** [comment]
If you could extensively test out the PR and make sure everything works as expected, that would be :sparkles:.  Additionally, if you think you are capable of reviewing the PR itself, feel free to do that as well :).
