### ISSUE TITLE
More flexible control cursor position

### ISSUE THREAD

**Issue by yisibl** [atom/autocomplete-css#39]
Like emmet:

``` js
"box-shadow:${1:inset }${2:hoff} ${3:voff} ${4:blur} ${5:color};"
```

https://github.com/emmetio/emmet/blob/master/lib/snippets.json#L156

**Comment by lee-dohm** [comment]
Are you suggesting a snippet for use in CSS? If so, this belongs on the [language-css package](https://github.com/atom/language-css). If you're not, could you give a little more information?

**Comment by winstliu** [comment]
No response, closing.
