### ISSUE TITLE
a list of values for the parameter "overflow:" not work correctly 

### ISSUE THREAD

**Issue by Akiyamka** [atom/autocomplete-css#43]
![list css](https://cloud.githubusercontent.com/assets/6587585/14105075/efc8d6a0-f5b1-11e5-8fd4-00463af7516d.png)

**Comment by albell** [comment]
This appears to be fixed in current builds:

![screen shot 2016-08-19 at 10 24 07 am](https://cloud.githubusercontent.com/assets/1142025/17818167/2be35e0c-65f7-11e6-817a-a79ee01f9902.png)

**Comment by winstliu** [comment]
Thanks for the update @albell!
