### ISSUE TITLE
Complete with Tab is different than Enter

### ISSUE THREAD

**Issue by MartinMuzatko** [atom/autocomplete-css#45]
Hello there!

Since I use atom, with or without additional packages, I have a really weird bug in css autocompletion.
While `Enter` works as expected, `Tab` uses always the first completion offered via the autocomplete menu and inserts `:` and `;` immediately.

`Enter` selects the item from the list where my cursor is.

So is there any other option that overwrites that? I'd be curious where that problem comes from.
As I prefer to autocomplete with tab and not with enter, this is really disturbing my workflow.

**Debugging Infos:**
Atom Version: 1.6.0

**Currently used packages:**

atom-language-velocity
atom-typescript
auto-detect-indentation
auto-reveal-active-file
color-picker
emmet
keybinding-cheatsheet
language-log
language-qml
language-ts
material-syntax
minimap
minimap-cursorline
minimap-find-and-replace
minimap-git-diff
minimap-highlight-selected
minimap-pigments
minimap-selection
monokai-seti
pigments
project-jump
seti-icons
seti-syntax
seti-ui
set-syntax
sublime-block-comment
tree-view-git-branch

**Comment by ElliottRoche** [comment]
I've got the same issue. Hitting tab just inserts `: ;` without actually completing anything.

![2016-04-04 at 1 11 pm](https://cloud.githubusercontent.com/assets/3212954/14258177/de1b331c-fa66-11e5-8174-1d2cfcefbe4f.gif)

**Comment by MartinMuzatko** [comment]
Thanks for the GIF!

**Comment by ElliottRoche** [comment]
@MartinMuzatko If you disable Emmet does autocomplete work for you?

I was just disabling packages one by one trying to see if there was some kind of problem there, and turning off Emmet seems to have fixed the issue for me.

**Comment by MartinMuzatko** [comment]
Yep, it is emmets fault. Thank you for clearing this up.
