### ISSUE TITLE
Suggestions should be offered in order of usefulness, not alphabetically

### ISSUE THREAD

**Issue by gregplaysguitar** [atom/autocomplete-css#5]
For example, when I type 

```
p {
    w
```

I get `whitespace` and `widows` before `width`. 99.9% of the time I'm after `width`, and I suspect this is true of most devs. I can imagine some won't like this so I guess it should be optional. 

Also, I realise I can easily implement this myself by setting a different source for css properties, but I'm not sure if that's the best general solution?

**Comment by gregplaysguitar** [comment]
Actually, I was able to implement this by bumping a few selected properties from the original source file to the top - see https://github.com/gregplaysguitar/autocomplete-css/commit/a087062e4be075798036a66d8123f56c8582bf8d

This way updates to the brackets CSSProperties.json will still come through without having to maintain a separate list.

**Comment by benogle** [comment]
I like your approach. You should make a PR

**Comment by gregplaysguitar** [comment]
Ok, so you're happy for this to be the default ordering, and not have an option for alphabetical? It is a bit subjective.

**Comment by benogle** [comment]
Yeah, they should be weighted by what the user is most likely to pick

**Comment by postcasio** [comment]
Chrome's property usage stats may be of some help https://www.chromestatus.com/metrics/css/popularity

—

**Comment by thomasjo** [comment]
> Chrome's property usage stats may be of some help https://www.chromestatus.com/metrics/css/popularity

Woah, I had no idea such a thing existed! Awesome :metal:
