### ISSUE TITLE
Not working!!!

### ISSUE THREAD

**Issue by AsenCME** [atom/autocomplete-css#59]
I need some help with this. The core css autocomplete doesn't work and so doesn't this one! How do I resolve this issue?

**Comment by winstliu** [comment]
Please read [How Do I Submit A (Good) Bug Report?](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) and open a new issue following those guidelines.  Thanks!
