### ISSUE TITLE
Alphabetize the properties in completions.json?

### ISSUE THREAD

**Issue by albell** [atom/autocomplete-css#61]
They're really all over the place right now. Not sure how this happened, or if there's a reason for it. Minor point, but it's a bit confusing.

FWIW the <a href="https://github.com/adobe/brackets/blob/master/src/extensions/default/CSSCodeHints/CSSProperties.json">Brackets</a> properties file the readme references is alphabetized.

**Comment by winstliu** [comment]
They're arbitrarily sorted using the order in [`sorted-property-names.json`](https://github.com/atom/autocomplete-css/blob/bf37cd8cf007f4acf0785944b2734715828b1ec4/sorted-property-names.json).  The idea being that the most-used properties will be suggested before lesser-used ones.
