### ISSUE TITLE
BUG: Broken after "split down"

### ISSUE THREAD

**Issue by Olian04** [atom/autocomplete-css#64]
The autocomplete stopped working after i split the view in 2 using the "split down" option, and then resized the lower window (the one with the css), (i made it smaller, about 20% of the screen height).
It still works in the ordinary window (the upper one), but it wont trigger at all (even with ctrl-space) in the lower window.

![screenshot from 2016-08-28 13-36-31](https://cloud.githubusercontent.com/assets/5493406/18033436/806b0482-6d24-11e6-852c-3beb4beaec2c.png)

**NOTE:** 
I realize this might not be a bug since the autocomplete menu wouldn't relay fit in the small window. Although i would still like it to work, maybe just make the menu scale with the size of the window? 

**Another bug?**
I just realized something, if i have the same css open in both windows, when i target the lower window and start typing, the menu shows up in the upper one.

**Comment by winstliu** [comment]
/cc @maxbrunsfeld - this was fixed recently, right?

EDIT: Yeah, it looks like it was: atom/atom#12522.  In the future @Olian04 please include the Atom version and OS you're using, as well as whether you can reproduce the issue in safe mode.

**Comment by maxbrunsfeld** [comment]
The fix will be released in Atom v1.10.0 and v1.11.0-beta0. We're planning on publishing these tomorrow, I believe.
