### ISSUE TITLE
Missing colon when writing inline CSS

### ISSUE THREAD

**Issue by LoDef** [atom/autocomplete-css#68]
I code a lot of email designs, where inline CSS is a neccessary evil as some email clients, like Gmail, strip out the CSS in `<head>`. 
The bug I'd like to raise attention to is small but still horribly annoying. For example, if I want to achieve this:
`<td style="line-height: 18px`
... I'd start typing `li` and get the `line-height` auto-complete option and press Enter, but always end up without the `:`, and have to type it manually, even though there is no situation where I would NOT want one (or is there? if so please tell me!).

**Comment by winstliu** [comment]
What Atom version are you using, and what OS?  Is this reproducible in safe mode (`atom --safe`)?  Does this also happen in `.css` files?

**Comment by LoDef** [comment]
I'm using Atom 1.10.2 on Windows 7 Professional 64 bit.
Yes, the issue is the same in safe-mode.

This issue doesn't apply to `.css` files as they contain no HTML to inline.

How to reproduce: Create a `.html` file with some basic markup. Create a table and put some styling to a `td` for example.

**Comment by winstliu** [comment]
Ok.  This isn't a bug with autocomplete-css.  Rather, it's because language-html isn't tokenizing the `style` attribute as CSS, so autocomplete-css has no idea that CSS is being written.  Can you please open a new issue on language-html instead?  Thanks!
