### ISSUE TITLE
Autocomplete-css doesn't support sass or scss

### ISSUE THREAD

**Issue by mgallardo** [atom/autocomplete-css#7]
It would be great if this could be done, this issue makes me think about going back to Sublime. So please, go for it! Thank you so much!

**Comment by kevinsawicki** [comment]
What isn't working?

You should get autocompletions for property names and values in Sass, SCSS, Less, and CSS.

Can you provide a code snippet or screenshot of the missing completions?

**Comment by mgallardo** [comment]
I didn't know you were supporting Sass too. In my case, it doesn't complete any property names at all.
Here is a screenshot; as you can see padding isn't autocompleting.

![ddd](https://cloud.githubusercontent.com/assets/881180/7153808/d35530b0-e34f-11e4-86a6-b84fedccc79d.png)

 Thank you so much.

**Comment by thomasjo** [comment]
Currently `autocomplete` does not provide completions _as you type_, you have to invoke the `autocomplete:toggle` command, which by default has keybinding <kbd>ctrl</kbd> + <kbd>space</kbd>.

If you want _as you type_ support, consider installing [`autocomplete-plus`](https://atom.io/packages/autocomplete-plus) (which will replace `autocomplete` in the near future).

**Comment by saschagehlich** [comment]
+1

No support for SASS right now, as the scope is set to `.source.css` only

**Comment by saschagehlich** [comment]
I took a quick look at it and added .source.sass to the provider scope. The problem is that with sass and its indented syntax, the editor can't know if you're writing a property name or a tag name

Example:

``` sass
.footer
  tab
```

If you have this code and your cursor is after `tab`, you might either want to write `table` (tag completion) or `table-layout` (property name completion). So we'd have to change a lot of this package's behavior. Maybe it makes more sense to create a separate `autocomplete-sass` package?

**Comment by lee-dohm** [comment]
Yeah, given the unique challenges to the Sass syntax, I think a separate provider would be best.

**Comment by benogle** [comment]
> Yeah, given the unique challenges to the Sass syntax, I think a separate provider would be best.

:+1:

**Comment by saschagehlich** [comment]
Working on it already - should be ready soon :)

**Comment by saschagehlich** [comment]
https://atom.io/packages/autocomplete-sass

Easy peasy.

**Comment by benogle** [comment]
@saschagehlich is the logic a whole lot different than the css provider? Maybe it should be added to the css provider to reduce effort/code duplication?

**Comment by benogle** [comment]
Also :+1: for putting it together so quickly

**Comment by benogle** [comment]
And I realize I totally changed my mind. :P. But I skimmed the code and it looked largely the same.

**Comment by saschagehlich** [comment]
Yeah it's not a huge difference, but the specs would work differently as the suggestions changed. But it should be quite easy to merge into autocomplete-css. I'll take a look at it later!

**Comment by oraculus** [comment]
@saschagehlich the autocomplete-sass don’t work on SCSS files. I would had left the bug report on that package git but is not possible ;)

**Comment by chrisdrackett** [comment]
@saschagehlich I also would have left an issue there, but it would be nice to grab variable and mixin names out of sass files in the project that aren't currently open.

**Comment by benogle** [comment]
SASS support added in #13
