### ISSUE TITLE
Package.activateConfig is deprecated.

### ISSUE THREAD

**Issue by zetay** [atom/autocomplete-css#8]
Use a config schema instead. See the configuration section
of https://atom.io/docs/latest/hacking-atom-package-word-count and
https://atom.io/docs/api/latest/Config for more details

```
Package.activateConfig (D:\GreenSoft\Atom\resources\app\src\package.js:247:11)
Package.activateNow (D:\GreenSoft\Atom\resources\app\src\package.js:218:14)
```

**Comment by thomasjo** [comment]
Thanks for reporting, but these are _false positives_ — this package has neither activation commands nor config schema.

---

/cc @izuzak @atom/non-github-maintainers
Could this be an issue in a provider used by this package?
