### ISSUE TITLE
Inline autocompletion uses the autocompletion values of the last property on the line

### ISSUE THREAD

**Issue by mino182** [atom/autocomplete-css#83]
Hi, when I write css property between another properties, or at begin of properties, hints from autocomplete-css belong to last written property. When I write new property on end, hint is right.

example:
![atom autocomplete-css bug](https://cloud.githubusercontent.com/assets/11948894/22626752/2bd9eacc-ebb5-11e6-9885-e74eb678a5a6.gif)

Atom v 1.13.1
autocomplete-css 0.14.1

**Comment by winstliu** [comment]
Darn, I thought I fixed all the inline bugs :/.
