### ISSUE TITLE
autocomplete-css doesn't work with language-postcss

### ISSUE THREAD

**Issue by evanyangg** [atom/autocomplete-css#84]
1. install language-postcss and create new css file like this 
![image](https://cloud.githubusercontent.com/assets/22952321/22768643/75feaaa0-eebe-11e6-8e62-b780191fd9fd.png)
grammar judgment is correct but autocomplete-css doesn't work
what should I do? 
thanks !!!

**Comment by winstliu** [comment]
You should subscribe to #37 for updates.
