### ISSUE TITLE
Suggestions firing on percentage key ie 100%

### ISSUE THREAD

**Issue by sebszocinski** [atom/autocomplete-css#96]
![image](https://cloud.githubusercontent.com/assets/5466694/26332694/96299bd0-3f97-11e7-985f-981216b3ffdd.png)
How can I prevent the suggestion box from appearing when typing %?

This is in a SASS file

**Comment by lee-dohm** [comment]
I was able to reproduce this using Atom v1.19.0-dev-efa440f70 on Mac OS X 10.12.4.

**Comment by winstliu** [comment]
Tricky because technically we're still completing a property value.  Just checking if the prefix is `:` isn't going to cut it because some CSS properties allow multiple property values (eg `margin: 10% auto auto 2%`).

The prefix that ac+ passes in doesn't count the `%`.

**Comment by sebszocinski** [comment]
Update, this actually happens on ANY of the SHIFT modifier keys ie: `~!@#$%^&*`

**Comment by sebszocinski** [comment]
Hi, thanks for fixing and closing and sorry for the rookie question, but how do I go about getting this update?

**Comment by winstliu** [comment]
It will be included in Atom 1.19.0.

**Comment by sebszocinski** [comment]
Great thanks

**Comment by sebszocinski** [comment]
Just posted an update in the [PR](https://github.com/atom/autocomplete-css/pull/97) that this is also happening on comma keys.. it also seems like it's just ignoring the `Minimum Word Length` in the Autocomplete-plus settings...

![image](https://user-images.githubusercontent.com/5466694/28447905-0b3b124c-6e13-11e7-9e78-57500a5bbb01.png)

![image](https://user-images.githubusercontent.com/5466694/28447935-3e01ade4-6e13-11e7-8fc9-7be772f83992.png)
